server:
  port: 8001
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sd1990/CloudConfigData
      native:
        searchLocations: E:\github\spring-cloud-config\config-server\src\main\resources\props.properties